// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Slowhigh/gogger/producer/infra/producer"
	"github.com/Slowhigh/gogger/producer/infra/router"
	"github.com/Slowhigh/gogger/producer/internal/adapter/controller/http"
	"github.com/Slowhigh/gogger/producer/internal/usecase/message"
	"github.com/memphisdev/memphis.go"
)

// Injectors from wire.go:

func InitializeServer(conn *memphis.Conn) (router.Router, error) {
	interactorProducer, err := producer.NewProducer(conn)
	if err != nil {
		return router.Router{}, err
	}
	messageUsecase := message.NewMessageUsecase(interactorProducer)
	controller := http.NewController(messageUsecase)
	routerRouter := router.NewRouter(controller)
	return routerRouter, nil
}
