// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Slowhigh/gogger/producer/infra/config"
	"github.com/Slowhigh/gogger/producer/infra/producer"
	"github.com/Slowhigh/gogger/producer/infra/router"
	"github.com/Slowhigh/gogger/producer/internal/adapter/controller/http"
	"github.com/Slowhigh/gogger/producer/internal/usecase/message"
)

// Injectors from wire.go:

func InitServer() (router.Router, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return router.Router{}, err
	}
	interactorProducer, err := producer.NewProducer(configConfig)
	if err != nil {
		return router.Router{}, err
	}
	messageUsecase := message.NewMessageUsecase(interactorProducer)
	controller := http.NewController(messageUsecase)
	routerRouter := router.NewRouter(configConfig, controller)
	return routerRouter, nil
}
