// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Slowhigh/gogger/consumer/infra/config"
	"github.com/Slowhigh/gogger/consumer/infra/consumer"
	"github.com/Slowhigh/gogger/consumer/infra/database"
	"github.com/Slowhigh/gogger/consumer/infra/database/repository"
	"github.com/Slowhigh/gogger/consumer/internal/adapter/controller"
	"github.com/Slowhigh/gogger/consumer/internal/usecase/message"
)

// Injectors from wire.go:

func InitServer() (*consumer.Consumer, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	databaseDatabase, err := database.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	accessLog, err := repository.NewAccessLog(databaseDatabase)
	if err != nil {
		return nil, err
	}
	messageUsecase := message.NewMessageUsecase(accessLog)
	controller := controller.NewController(messageUsecase)
	consumerConsumer, err := consumer.NewConsumer(configConfig, controller)
	if err != nil {
		return nil, err
	}
	return consumerConsumer, nil
}
