name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './producer/go.mod'

      - name: Build producer
        working-directory: ./producer
        run: go build -v -o ./server ./cmd/server

      - name: Test producer
        working-directory: ./producer
        run: go test -v ./cmd/server