name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go: [ '1.19.x', '1.20.x', '1.21.x' ]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: ./producer

      - run: ls -al

      - run: cd ./producer

      - run: ls -al

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build producer
        run: go build -v -o ./server ./cmd/server

      - name: Test producer
        run: go test -v ./cmd/server